version: '3'

services:
  ab-short-url:
    ports:
    - "8080:8080"
    build:
      context: ./
      dockerfile: Dockerfile
  postgres:
    restart: always
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres

networks:
  spring-cloud-network:
    driver: bridge