version: '3'

services:
  web:
    build: .
    ports:
    - "8080:8080"
  postgres96:
    restart: always
    image: postgres:9.6
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin@123
      POSTGRES_USER: postgres