server:
  port: 8080

spring:
  application:
    name: ab-short-url
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/postgres
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

ribbon:
  ServerListRefreshInterval: 1000

management:
  endpoints:
    web:
      exposure:
        include: "*"

ip: localhost