server:
  port: 8080

spring:
  application:
    name: App
  h2:
    console:
      enabled: true

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
